@katori_HostAddress = http://localhost:5014

# get list of journals
GET {{katori_HostAddress}}/api/journal/getJournals
Accept: application/json

###


# add a new journal
POST {{katori_HostAddress}}/api/journal/setjournal
Content-Type: application/json

{
    "particular1":"Cash",
    "particular2":"Purchase",
    "comment":"we need more money to pay the insurance!",
    "debit":"9999",
    "credit":"12",
    "date":"3012-04-12"
}

###

# get all particulars
GET {{katori_HostAddress}}/api/particular/getParticulars
Accept: application/json

###

# create a new ledger
POST {{katori_HostAddress}}/api/ledger/setledger
Content-Type:application/json

{
    "title":"cash",
    "ledgertype":"credit"
}


###

# get all ledgers
@var1=purchase
GET  {{katori_HostAddress}}/api/ledger/getledgers?title={{var1}}
Accept: application/json

###

@var2=cash
GET  {{katori_HostAddress}}/api/ledger/getledgers?title={{var2}}
Accept: application/json